version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: grooftop_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: grooftop
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: grooftop_backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@192.168.0.4:5432/grooftop?schema=public"
      JWT_SECRET: "your-generated-secret-key"
      JWT_EXPIRATION: "24h"
      PORT: 3000
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    command: >
      sh -c "npx prisma migrate dev &&
             npx prisma db seed &&
             npm run start:dev"
             
volumes:
  db_data:
